[phases.setup]
nixPkgs = ["php81", "php81-extensions", "composer"]
phpPkgs = ["intl", "zip", "mbstring", "openssl", "pdo", "sqlite3", "bcmath"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]