FROM node:22

WORKDIR /var/www

COPY docker/node/startup-dev.sh /usr/local/bin/startup-dev.sh
RUN chmod +x /usr/local/bin/startup-dev.sh

ENTRYPOINT ["/usr/local/bin/startup-dev.sh"]
CMD ["npm", "run", "dev", "--", "--host", "--port", "5173"]